#!/bin/bash

#
# TODO: Search for word list within each script and execute set_tab_completion automatically.
#
set_tab_completion lzhelp "${LZ_PUBLIC_FUNCTIONS[*]} ${LZ_PUBLIC_SCRIPT_BASE_NAMES[*]}"

