#!/bin/bash

#
# _bash_welcome.sh
#
#  Created on: 2018-05-28
#
#      Author: WenXiongchang (udc577@126.com)
#
# Description: Hints displayed on terminal when this script is imported.
#
#       Usage: This script should be used by inner modules only.
#

RECOMMENDED_COLUMNS=120

if [ $COLUMNS -lt $RECOMMENDED_COLUMNS ]
then
	_EXPECTED_COLUMNS=$COLUMNS
else
	_EXPECTED_COLUMNS=$RECOMMENDED_COLUMNS
fi

for ((i = 0; i < $_EXPECTED_COLUMNS; i++)); do printf "#"; done
echo ""
echo "###"
echo "### Operating system: $OS_NAME $OS_FULL_VERSION"
#echo "###"
#echo "### Shell: $SHELL"
echo "###"
echo "### Home directory of Lazy-script: $LAZY_SCRIPT_HOME"
echo "###"
echo "### Author: Wen Xiongchang(Email: udc577@126.com; GitHub: FooFooDamon)"
echo "###"
for ((i = 0; i < $_EXPECTED_COLUMNS; i++)); do printf "#"; done
echo ""
echo "Several tips:"
echo "1. Recommended terminal width: $RECOMMENDED_COLUMNS characters or above"
echo "2. To record your operations in terminal, run: tl"
echo "3. To view all public functions and scripts, run: lzhelp"
echo "4. To see detailed usage of one or more function(s) or script(s), run: lzhelp <name 1> <name 2> ..."
echo "   Luckly, lzhelp supports tab completion, just try it!"
echo "Enjoy!"

