#!/bin/bash

#
# _bash_settings.sh
#
#  Created on: 2018-05-28
#
#      Author: WenXiongchang (udc577@126.com)
#
# Description: Common settings.
#
#       Usage: This script should be used by inner modules only.
#

###############################################
###
### Generally settings
###
###############################################

if [ "$BASH_SOURCE" = "$0" ]
then
	echo -e "\e[0;31m*** $(basename $BASH_SOURCE) can not be executed directly! Use it as below:\e[0m" >&2
	echo "    . \"$BASH_SOURCE\"" >&2
	echo "or:" >&2
	echo "    source \"$BASH_SOURCE\"" >&2
	exit 1
fi

_NECESSARY_TOOLS=(expect perl python3 vim)

_NECESSARY_DIRS=($HOME/bin \
	$HOME/etc \
	$HOME/include \
	$HOME/lib \
	$HOME/docs \
	$HOME/logs \
	$HOME/src \
	$__LAZY_SCRIPT_HOME__/details/private \
	$__LAZY_SCRIPT_HOME__/details/private/vim)

env_var_push_front PATH $HOME/bin $__LAZY_SCRIPT_HOME__/details $__LAZY_SCRIPT_HOME__/details/shortcuts $__LAZY_SCRIPT_HOME__/details/private

env_var_push_front LD_LIBRARY_PATH /usr/local/lib $HOME/lib
env_var_push_front PYTHONPATH $__LAZY_SCRIPT_HOME__/lib/customized_python_libraries

alias sudo="sudo env LAZY_SCRIPT_HOME=$__LAZY_SCRIPT_HOME__ PATH=$PATH LD_LIBRARY_PATH=$LD_LIBRARY_PATH PYTHONPATH=$PYTHONPATH"

export CPU_CORES=`cat /proc/cpuinfo | grep "processor" | wc -l`
alias make="time make"
alias jmake="time make -j $CPU_CORES"
alias vmake="time make VERBOSE=1"
alias vjmake="time make -j $CPU_CORES VERBOSE=1"
alias dmake="time make DEBUG=1"
alias djmake="time make -j $CPU_CORES DEBUG=1"
alias amake="time make -j $CPU_CORES DEBUG=1 VERBOSE=1" # means executing make with [a]ll options above

alias valgrind="valgrind --tool=memcheck --leak-check=full --track-origins=yes --show-reachable=yes --log-file=valgrind_report.log"
alias pugrep="pgrep -u $USER"
alias pst="ps -eLo ruser,pid,ppid,lwp,psr,args" # means displaying [t]hread info while executing ps
alias L="cd $__LAZY_SCRIPT_HOME__"
alias LP="cd $__LAZY_SCRIPT_HOME__/details/private"
alias dsk="cd $HOME/桌面 2> /dev/null || cd $HOME/Desktop"
alias startx="echo -e \"\\e[0;33mstartx should not be used when you have entered a graphic desktop\\e[0m\""
alias soft_bg_colors=soft_background_colors
alias tabs_to_spaces="expand"
alias tabs_to_4spaces="expand -t 4"
alias clear_swapness="sync;sudo swapoff -a;sudo swapon -a"
#alias rm=mv $* $HOME/Trash
alias rm=safer-rm
alias tl="script -f $HOME/logs/terminal_log_\`date +%Y-%m-%d_%H_%M_%S\`.txt"

###############################################
###
### Settings depending on platforms
###
###############################################

# TODO: more platforms and more settings.
if [ "`to_lower_case $OS_NAME`" = "cygwin" ]
then
	VIMRC=$HOME/_vimrc
else
	VIMRC=$HOME/.vimrc
fi

